---
title: "Titanic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(tidyr)
library(modelr)
library(purrr)
library(tibble)

library(randomForest)
library(e1071)
```

# Data import

```{r}
train <- readr::read_csv('~/Code/data/kaggle/titanic_train.csv')
train$Age[is.na(train$Age)] <- mean(na.omit(train$Age))
train$Sex <- factor(train$Sex)
train$Embarked[is.na(train$Embarked)] <- names(which.max(table(train$Embarked)))
train$Embarked <- factor(train$Embarked)
train$CabinType <- stringr::str_sub(train$Cabin, 1, 1)
train$CabinType[is.na(train$CabinType)] <- 'Z'
train$CabinType[train$CabinType %in% c('G', 'T')] <- 'Z'
train$CabinType <- factor(train$CabinType)
```

```{r}
train_cv <- crossv_kfold(train, 10)

summary_fn <- function(x) {
  avs <- list(mean = mean(x), sd = sd(x), length = length(x))
  return(paste0(round(avs$mean, 2), ' +/- ', round(avs$sd / sqrt(avs$length), 2)))
}
```

## Logistic regression

```{r}
accuracy <- function(model, data) {
  x <- predict(model, data, type = 'response')
  x <- ifelse(x > 0.5, 1, 0)
  actual <- as_tibble(data)[[all.vars(model$formula[[2]])]]
  return(mean(x == actual))
}

model1 <- ~ glm(Survived ~ Sex, family = binomial, data = .)
model2 <- ~ glm(Survived ~ Pclass + Sex, family = binomial, data = .)
model3 <- ~ glm(Survived ~ Pclass + Sex + Age + SibSp + Parch + Embarked + Fare + CabinType, 
                family = binomial, data = .)

models <- c('Sex' = model1, 'Sex+Pclass' = model2, 'AllApplicable' = model3)

results_fn <- function(model) {
  train_cv %>%
    mutate(train = map(train, as_tibble)) %>%
    mutate(model = map(train, model)) %>%
    mutate(train_accuracy = map2_dbl(model, train, accuracy),
           test_accuracy = map2_dbl(model, test, accuracy))
} 

results <- map(models, results_fn)
print(map(results, 'train_accuracy') %>% map_chr(summary_fn))
print(map(results, 'test_accuracy') %>% map_chr(summary_fn))
```

```{r}
fitted <- results[[3]][[1, 4]]
test <- results[[3]][[1, 2]]
x <- predict(fitted, test, type = 'response')
x <- ifelse(x > 0.5, 1L, 0L)

confused <- function(prediction, actual) {
  tibble(p = prediction, a = actual, count = 1L) %>%
    group_by(p, a) %>%
    summarize(c = sum(count)) %>%
    spread(p, c)
}

tbl <- confused(x, as_tibble(test)$Survived)
print(tbl)
```

## Random forest

```{r}
accuracy <- function(model, data) {
  x <- predict(model, data, type = 'response')
  actual <- as_tibble(data)[[as.character(model$terms[[2]])]]
  return(mean(x == actual))
}

model1_rf <- ~ randomForest(Survived ~ Sex, data = .)
model2_rf <- ~ randomForest(Survived ~ Sex + Pclass, data = .)
model3_rf <- ~ randomForest(Survived ~ Pclass + Sex + Age + SibSp + Parch + Embarked + 
                              Fare + CabinType, data = .)

models <- c('RF-Sex' = model1_rf, 'RF-Sex+Pclass' = model2_rf, 'RF-AllApplicable' = model3_rf)

results_fn <- function(model) {
  set.seed(121)
  train_cv %>%
    mutate(train = map(train, as_tibble)) %>%
    mutate(train = map(train, ~ mutate(., Survived = factor(Survived)))) %>%
    mutate(model = map(train, model)) %>%
    mutate(train_accuracy = map2_dbl(model, train, accuracy),
           test_accuracy = map2_dbl(model, test, accuracy))
} 

results <- map(models, results_fn)
print(map(results, 'train_accuracy') %>% map_chr(summary_fn))
print(map(results, 'test_accuracy') %>% map_chr(summary_fn))
```

```{r}
fitted <- results[[3]]$model[[1]]
imp <- importance(fitted)
print(imp[rev(order(imp[, 1])), ])
```

```{r}
mtries <- c(1, 2, 3, 4)
models <- map(mtries, function(mtry) {
  mt <- mtry
  ~ randomForest(Survived ~ Pclass + Sex + Age + SibSp + Parch + Embarked + Fare, data = .,
                 mtry = mt)
})

results <- map(models, results_fn)
print(map(results, 'train_accuracy') %>% map_chr(summary_fn))
print(map(results, 'test_accuracy') %>% map_chr(summary_fn))
```

```{r}
ntrees <- c(2, 50, 100, 500)
models <- map(ntrees, function(ntree) {
  nt <- ntree
  ~ randomForest(Survived ~ Pclass + Sex + Age + SibSp + Parch + Embarked + Fare, data = .,
                 ntree = nt)
})

results <- map(models, results_fn)
print(map(results, 'train_accuracy') %>% map_chr(summary_fn))
print(map(results, 'test_accuracy') %>% map_chr(summary_fn))
```

## SVM

```{r}
accuracy <- function(model, data) {
  x <- predict(model, as_tibble(data))
  actual <- as_tibble(data)[[as.character(model$terms[[2]])]]
  return(mean(x == actual))
}

model1_svm <- ~ svm(Survived ~ Sex, data = .)
model2_svm <- ~ svm(Survived ~ Sex + Pclass, data = .)
model3_svm <- ~ svm(Survived ~ Pclass + Sex + Age + SibSp + Parch + Embarked + 
                      Fare + CabinType, data = .)

models <- c('svm-Sex' = model1_svm, 'svm-Sex+Pclass' = model2_svm, 'svm-AllApplicable' = model3_svm)

results_fn <- function(model) {
  train_cv %>%
    mutate(train = map(train, as_tibble)) %>%
    mutate(train = map(train, ~ mutate(., Survived = factor(Survived)))) %>%
    mutate(model = map(train, model)) %>%
    mutate(train_accuracy = map2_dbl(model, train, accuracy),
           test_accuracy = map2_dbl(model, test, accuracy))
} 

results <- map(models, results_fn)
print(map(results, 'train_accuracy') %>% map_chr(summary_fn))
print(map(results, 'test_accuracy') %>% map_chr(summary_fn))
```
